spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: ${accounts.datasource.url}
    username: ${accounts.datasource.username}
    password: ${accounts.datasource.password}
  jpa:
    database: ${accounts.jpa.database}
    show-sql: ${accounts.jpa.show-sql}
    hibernate:
      ddl-auto: ${accounts.jpa.hibernate.ddl-auto}

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

eureka:
  client: ${eureka-client}

application:
  allow-get-accounts: ${accounts.allow-get-accounts}

